version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t lambda/
  build:
    commands:
      - echo "Linting..."
      - pylint lambda/handler.py || true
artifacts:
  files:
    - template.yaml
    - lambda/**/*
